version: '3'

services:
  headless-lightning:
    restart: always
    build: .

    volumes:
      - ./:/var/www/html

    ports:
      - "80:80"
    networks:
      - dhl

  mariadb:
    restart: always
    image: mariadb:10.3.11

    volumes:
      - database:/var/lib/mysql
    env_file:
      - ./mysql.env

    networks:
      - dhl

networks:
  dhl:

volumes:
  database:
