version: '3'

services:
  headless-lightning:
    restart: always
    build: .

    volumes:
      - ./webroot:/var/www/html
      - ./mysql.env:/environment/mysql.env

    ports:
      - "8082:80"
    networks:
      - dhl

  mariadb:
    restart: always
    image: mariadb:10.3.11

    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - ./mysql.env

    networks:
      - dhl

networks:
  dhl:
