access_ui: 1.4.0-beta1
blazy: 1.0.0-rc4
block: 8.6.4
block_content: 8.6.4
breakpoint: 8.6.4
ckeditor: 8.6.4
config: 8.6.4
consumers: 1.2.0
content_model_ui: 1.4.0-beta1
content_moderation: 8.6.4
crop: 2.0.0-rc1
ctools: 3.0.0
datetime: 8.6.4
dblog: 8.6.4
diff: 1.0.0-rc2
dropzonejs: 2.0.0-alpha3
editor: 8.6.4
embed: 1.0.0
entity_block: 1.0.0-beta1
entity_browser: 2.0.0
entity_embed: 1.0.0-beta2
entity_reference: 8.6.4
field: 8.6.4
field_ui: 8.6.4
file: 8.6.4
filter: 8.6.4
headless_ui: 1.4.0-beta1
help: 8.6.4
image: 8.6.4
image_widget_crop: 2.2.0
inline_entity_form: 1.0.0-rc1
json_content: 1.4.0-beta1
jsonapi: 1.24.0
libraries: 3.0.0-alpha1
lightning: 3.202.0
lightning_api: 2.8.0
lightning_core: 3.4.0
lightning_install: 3.202.0
link: 8.6.4
media: 8.6.4
media_library: 8.6.4
node: 8.6.4
openapi: 1.0.0-beta2
openapi_ui: 1.0.0-rc1
openapi_ui_redoc: 1.0.0-rc2
openapi_ui_swagger: 1.0.0-rc3
options: 8.6.4
page_cache: 8.6.4
path: 8.6.4
schemata: 1.0.0-alpha5
schemata_json_schema: 1.0.0-alpha5
serialization: 8.6.4
shortcut: 8.6.4
simple_oauth: 3.13.0
simple_oauth_extras: 3.13.0
system: 8.6.4
taxonomy: 8.6.4
text: 8.6.4
token: 1.5.0
toolbar: 8.6.4
user: 8.6.4
workflows: 8.6.4
menu_link_content: 8.6.4
views: 8.6.4
lightning_page: 3.4.0
lightning_roles: 3.4.0
views_infinite_scroll: 1.5.0
lightning_media: 3.4.0
lightning_media_audio: 3.4.0
lightning_media_bulk_upload: 3.4.0
lightning_media_document: 3.4.0
lightning_media_image: 3.4.0
media_entity_instagram: 2.0.0-alpha2
lightning_media_instagram: 3.4.0
slick: 1.1.0
slick_entityreference: 1.1.0
lightning_media_slideshow: 3.4.0
media_entity_twitter: 2.0.0-alpha2
lightning_media_twitter: 3.4.0
video_embed_field: 2.0.0
video_embed_media: 2.0.0
lightning_media_video: 3.4.0
lightning_workflow: 3.2.0
lightning_scheduler: 3.2.0
moderation_sidebar: 1.1.0
pathauto: 1.3.0
headless_lightning: 1.4.0-beta1
update: 8.6.4
entity_reference_revisions: 1.6.0
paragraphs: 1.5.0
views_ui: 8.6.4
rest: 8.6.4
